/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpuBoost */

#ifndef _Included_cpuBoost
#define _Included_cpuBoost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpuBoost
 * Method:    calculate
 * Signature: ([J[J[I)[J
 */
JNIEXPORT jlongArray JNICALL Java_cpuBoost_calculate
  (JNIEnv *, jobject, jlongArray, jlongArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
